### ISSUE TITLE
Does't work with custom variants like [&_.class]:(mt-10 mb-30)

### ISSUE THREAD

**Issue by AlexeyPavlyuck** [NazmusSayad/tailwind-variant-group#1]
Your work is cool, thank you!
Please add support custom variants

**Comment by NazmusSayad** [comment]
Sorry for the late reply, I was busy with exam...

## I can't get it. what do you mean by custom variant?

As far as I know you can use custom variants just like normal variants by configuring tailwind config.

Normal variant, `hover:(bg-red color-black)` means `hover:bg-red hover:color-black`

What does `[&_.class]:(mt-10 mb-30)` means??

**Comment by NazmusSayad** [comment]
## I have added the feature.

One of my friend told me about this:
![image](https://github.com/NazmusSayad/tailwind-variant-group/assets/87106526/6f6bbcbd-0b53-4610-947d-63a416ee2c13)
